# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_badge',
            field=models.BooleanField(default=False),
        ),
    ]
