# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-17 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bid_main', '0002_role_is_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last update'),
        ),
    ]
