# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 18:11
#
# Not sure why this migration is needed, but Django generated it for us.
#
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_main', '0003_user_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='bid_main.Role'),
        ),
    ]
