# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_main', '0005_roles_may_manage_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('use_store_api', 'Can use the store API to manage users'),), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='role',
            name='may_manage_roles',
            field=models.ManyToManyField(blank=True, help_text='Users with this role will be able to grant or revoke these roles to any other user.', related_name='managers', to='bid_main.Role'),
        ),
    ]
