# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_main', '0005_roles_may_manage_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
