# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_main', '0006_role_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'A user with that email address already exists.'}, help_text='Required. 64 characters or fewer.', max_length=64, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='full name'),
        ),
    ]
